{
 "title": "TrueNAS Scale - Applications (k3s)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(uptime,job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(uptime{job=\"$job\"},instance)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(k3s_pod_cpu{instance=\"$instance\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "K3S Pod CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "k3s_pod_cpu{instance=~\"$instance\"} / 1000000000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "K3S Pod Memory",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k3s_pod_mem{instance=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "K3S Total Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(k3s_pod_net{instance=~\"$instance\"}[$__rate_interval])) by (instance,direction)",
     "legendFormat": "{{direction}} - {{instance}}"
    }
   ]
  },
  { "title": "POD: $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "pod" },
  {
   "title": "% CPU Time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k3s_pod_cpu{instance=~\"$instance\", pod=~\"$pod\"} / ($__interval_ms * 1000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "k3s_pod_cpu{instance=~\"$instance\", pod=~\"$pod\"} / 1000000000",
     "legendFormat": "% cpu time"
    }
   ]
  },
  {
   "title": "Pod Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "k3s_pod_mem{instance=~\"$instance\", pod=~\"$pod\"}",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Pod Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(k3s_pod_net{instance=~\"$instance\", pod=~\"$pod\"}[$__rate_interval])) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Net IN",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(k3s_pod_net{instance=~\"$instance\", pod=~\"$pod\", direction=\"incoming\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total MEM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k3s_pod_mem{instance=~\"$instance\", pod=~\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net OUT",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(k3s_pod_net{instance=~\"$instance\", pod=~\"$pod\", direction=\"outgoing\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}